# Generated by Django 3.2.18 on 2023-05-13 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20230513_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 7, 2, 20, 401490, tzinfo=utc)),
        ),
    ]
