# Generated by Django 3.2.18 on 2023-05-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='direction',
            new_name='directions',
        ),
    ]
